### ISSUE TITLE
Error installing XMLSchema in R 3.2.0

### ISSUE THREAD

**Issue by willgearty** [sckott/XMLSchema#1]
I'm trying to install XMLSchema for use with taxizesoap in R 3.2.0.
However, every time I try to install it fails.
I believe it was originally designed for an earlier version of R, is it perhaps no longer compatible?
The error is included below.
Thanks,
Will

```
> library(devtools)
> devtools::install_github(c("sckott/XMLSchema", "sckott/SSOAP"))
Downloading github repo sckott/XMLSchema@master
Installing XMLSchema
"C:/PROGRA~1/R/R-32~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/Will/AppData/Local/Temp/RtmpY7ljl6/devtools3310432e5709/sckott-XMLSchema-02c65a3"  \
  --library="C:/Users/Will/Documents/R/win-library/3.2" --install-tests 

* installing *source* package 'XMLSchema' ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in .mergeMethodsTable(generic, mtable, tt, attach) : 
  trying to get slot "defined" from an object of a basic class ("list") with no slots
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Users/Will/Documents/R/win-library/3.2/XMLSchema'
Error: Command failed (1)
```

**Comment by sckott** [comment]
hi, thanks for the issue

I should add to the readme - this is just a github forked version of the pkg by Duncan Templelang - To make installation easier - but I'll take a peak...

**Comment by willgearty** [comment]
Yeah, I've tried reaching out to Duncan as well, but any help you can provide would be immensely helpful!

**Comment by sckott** [comment]
@willgearty seems to install fine on R 3.1.3 and presumably older version too, though not tested

Looking through 3.2 changes to see if something pops out

**Comment by sckott** [comment]
seems to be related to this change in base R methods library 

https://github.com/wch/r-source/blame/37540722015d68a6a1eb195b761d01b470926dd0/src/library/methods/R/methodsTable.R#L76

Not sure where `.mergeMethodsTable` is called yet in xmlschema

**Comment by sckott** [comment]
@willgearty sorry, still haven't tracked down this bug...

**Comment by willgearty** [comment]
No worries! It's not too time sensitive!

**Comment by cboettig** [comment]
@willgearty @sckott I think the problem is just that the github version is stale?  Installing directly from the omegahat repo works for me (on Linux):

``` r
install.packages("XMLSchema", repo="http://www.omegahat.org/R")
```

**Comment by sckott** [comment]
right, that installs fine, but the version i have in this repo is a copy of a dev version from omegahat that's a diff version than at http://www.omegahat.org/R that actually seems to work for us in taxizesoap

**Comment by willgearty** [comment]
Just wanted to report I was able to successfully install XMLSchema 0.8-0 from http://packages.ropensci.org and https://github.com/omegahat/XMLSchema. Not sure what changed, but at least in R 3.3.1 this is no longer an issue.

Note: the omegahat.net version still does not install (http://www.omegahat.net/Prerelease/XMLSchema_0.8-0.tar.gz)

**Comment by sckott** [comment]
@willgearty thanks for the report, yeah, seems to be sorted. our instructions in readme already work for the current R version, so looks like we're all good. thanks again
